<a href="https://colab.research.google.com/github/vaibhavbansode86/smart_work/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("We are learning Numpy")

We are learning Numpy


In [2]:
import numpy as np

In [3]:
a = [[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2]]   ## nested list
arr1 = np.array(a)
arr1

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [5]:
b = [[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2],[230,30,20],[243,34,24],[243,43,42]]   ## nested list
arr2 = np.array(b)
arr2

array([[  2,   4,   5],
       [  5,   4,   5],
       [  6,   7,   8],
       [  9,   8,   7],
       [ 23,   3,   2],
       [230,  30,  20],
       [243,  34,  24],
       [243,  43,  42]])

In [38]:
b = [[[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2]]]   ## nested list
arr2 = np.array(b)
arr2

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]]])

In [10]:
c = [[[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2]],
     [[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2]]]   ## nested list
arr3 = np.array(c)
arr3

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]],

       [[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]]])

In [ ]:
len(arr1)

5

In [6]:
len(arr2)

8

In [39]:
len(arr3)

2

In [8]:
arr1.ndim

2

In [40]:
arr2.ndim

3

In [41]:
arr3.ndim

3

In [43]:
arr1.shape

(5, 3)

In [42]:
arr2

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]]])

In [9]:
arr2.shape

(8, 3)

In [44]:
arr3

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]],

       [[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]]])

In [11]:
arr3.shape

(2, 5, 3)

In [12]:
### Array Slicing

In [13]:
arr1

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [14]:
arr1[0]

array([2, 4, 5])

In [15]:
arr1[1]

array([5, 4, 5])

In [16]:
arr1[-2]

array([9, 8, 7])

In [17]:
arr1[:]

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [18]:
arr1[2:5]  ## from index 2 to index 4

array([[ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [19]:
arr1[2:6]

array([[ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [20]:
arr1[1:]

array([[ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [21]:
arr1[:4]   ## first to 3

array([[2, 4, 5],
       [5, 4, 5],
       [6, 7, 8],
       [9, 8, 7]])

In [22]:
arr1[3]

array([9, 8, 7])

In [23]:
arr1[3,1]

8

In [24]:
arr1

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [25]:
arr1[1:]

array([[ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [46]:
c = [[[2,4,5],[5,4,5],[6,7,8],[9,8,7],[23,3,2]],
     [[20,40,50],[90,49,59],[69,79,89],[99,8,97],[23,39,29]]]   ## nested list
arr3 = np.array(c)
arr3

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]],

       [[20, 40, 50],
        [90, 49, 59],
        [69, 79, 89],
        [99,  8, 97],
        [23, 39, 29]]])

In [47]:
arr3

array([[[ 2,  4,  5],
        [ 5,  4,  5],
        [ 6,  7,  8],
        [ 9,  8,  7],
        [23,  3,  2]],

       [[20, 40, 50],
        [90, 49, 59],
        [69, 79, 89],
        [99,  8, 97],
        [23, 39, 29]]])

In [48]:
arr3[1]

array([[20, 40, 50],
       [90, 49, 59],
       [69, 79, 89],
       [99,  8, 97],
       [23, 39, 29]])

In [49]:
arr3[0]

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [50]:
arr3[0][3]

array([9, 8, 7])

In [51]:
arr3[0][3][2]

7

In [52]:
arr3[0][1:4]

array([[5, 4, 5],
       [6, 7, 8],
       [9, 8, 7]])

In [53]:
arr3[0][1:4][2]

array([9, 8, 7])

In [54]:
arr3[0][1:4,2]

array([5, 8, 7])

In [55]:
arr1

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [27]:
arr1.mean()

6.533333333333333

In [28]:
arr1.sum()

98

In [29]:
arr1.sum(axis=0)  ##coluwn wise

array([45, 26, 27])

In [30]:
arr1.sum(axis=1)  ##row wise

array([11, 14, 21, 24, 28])

In [31]:
arr1.max()

23

In [32]:
arr1.min()

2

In [33]:
arr1

array([[ 2,  4,  5],
       [ 5,  4,  5],
       [ 6,  7,  8],
       [ 9,  8,  7],
       [23,  3,  2]])

In [56]:
arr1.argmax() #position of maximum number

12

In [35]:
arr1.argmin()

0

In [37]:
arr1.min(axis=1)

array([2, 4, 6, 7, 2])

In [57]:
## Linspace - Linear Spacing
np.linspace(20,40,5)

array([20., 25., 30., 35., 40.])

In [58]:
np.linspace(20,40,10)

array([20.        , 22.22222222, 24.44444444, 26.66666667, 28.88888889,
       31.11111111, 33.33333333, 35.55555556, 37.77777778, 40.        ])

In [59]:
np.arange(20,40,3)

array([20, 23, 26, 29, 32, 35, 38])

In [60]:
np.arange(20,41,3)

array([20, 23, 26, 29, 32, 35, 38])

In [61]:
np.arange(20,42,3)

array([20, 23, 26, 29, 32, 35, 38, 41])

In [62]:
### Random Function
np.random.randint(50)

12

In [63]:
np.random.seed(11225)
np.random.randint(50)

6

In [64]:
np.random.randint(50,500)

212

In [65]:
np.random.randint(50,500,10)

array([355, 147, 193, 380, 379, 400, 263, 128, 211, 124])

In [66]:
np.random.randint(50,500,(5,5))

array([[475, 387, 164,  74, 234],
       [475, 382, 264, 211, 205],
       [467, 170, 232, 195, 334],
       [464, 400, 393, 497, 315],
       [232, 287, 487, 231, 471]])

In [67]:
## Standard Matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.pi

3.141592653589793

In [71]:
np.exp(50)

5.184705528587072e+21

In [72]:
a = np.identity(5)
a = a.astype("int")
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [73]:
b = np.linspace(10,100,50)
b

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [74]:
np.round(b)

array([ 10.,  12.,  14.,  16.,  17.,  19.,  21.,  23.,  25.,  27.,  28.,
        30.,  32.,  34.,  36.,  38.,  39.,  41.,  43.,  45.,  47.,  49.,
        50.,  52.,  54.,  56.,  58.,  60.,  61.,  63.,  65.,  67.,  69.,
        71.,  72.,  74.,  76.,  78.,  80.,  82.,  83.,  85.,  87.,  89.,
        91.,  93.,  94.,  96.,  98., 100.])

In [75]:
np.round(b,3)

array([ 10.   ,  11.837,  13.673,  15.51 ,  17.347,  19.184,  21.02 ,
        22.857,  24.694,  26.531,  28.367,  30.204,  32.041,  33.878,
        35.714,  37.551,  39.388,  41.224,  43.061,  44.898,  46.735,
        48.571,  50.408,  52.245,  54.082,  55.918,  57.755,  59.592,
        61.429,  63.265,  65.102,  66.939,  68.776,  70.612,  72.449,
        74.286,  76.122,  77.959,  79.796,  81.633,  83.469,  85.306,
        87.143,  88.98 ,  90.816,  92.653,  94.49 ,  96.327,  98.163,
       100.   ])

In [76]:
np.sin(75)

-0.38778163540943045

In [77]:
np.cos(56)

0.8532201077225842

In [78]:
np.tan(88)

0.03542050133937693

In [79]:
arr1.shape

(5, 3)

In [80]:
arr1 = arr1.reshape(15,1)

In [81]:
arr1

array([[ 2],
       [ 4],
       [ 5],
       [ 5],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 8],
       [ 7],
       [23],
       [ 3],
       [ 2]])